"""MkDocs hook: render a top-of-page image on wiki PC, NPC, and location pages.

For any page under `wiki/pcs/`, `wiki/npcs/`, or `wiki/locations/`, if an asset named
after the page slug exists at `docs/assets/<category>/<slug>.{png,jpg,jpeg,webp}`,
inject it as a framed image right after the page's H1. Missing asset → page unchanged.

This lets images "just appear":
  - PC and NPC portraits are player-provided art dropped into docs/assets/pcs|npcs/.
  - Location art is generated from the location summary into docs/assets/locations/.

Wired in via `hooks: [hooks/wiki_images.py]` in mkdocs.yml — a native MkDocs
feature, so no extra pip dependency. The `.wiki-image` class is styled in
docs/stylesheets/extra.css. Requires the `attr_list` markdown extension (enabled
in mkdocs.yml) for the class to apply.
"""

import os

# Wiki categories that get a top-of-page image, in `wiki/<category>/` layout.
# PC and NPC images are user-dropped art; location images are AI-generated by the
# summarizer. All three are rendered here identically when the asset exists.
CATEGORIES = ("pcs", "npcs", "locations")
EXTENSIONS = (".png", ".jpg", ".jpeg", ".webp")


def _find_asset(docs_dir, category, slug):
    """Return the first existing asset path for this slug, or None."""
    for ext in EXTENSIONS:
        rel = os.path.join("assets", category, slug + ext)
        if os.path.isfile(os.path.join(docs_dir, rel)):
            return rel
    return None


def on_page_markdown(markdown, page, config, files):
    src_uri = page.file.src_uri  # e.g. "wiki/pcs/adarius.md"
    parts = src_uri.split("/")
    if len(parts) != 3 or parts[0] != "wiki" or parts[1] not in CATEGORIES:
        return markdown

    category = parts[1]
    slug = os.path.splitext(parts[2])[0]

    asset_rel = _find_asset(config["docs_dir"], category, slug)
    if asset_rel is None:
        return markdown

    # Path from this page (wiki/<category>/<slug>.md) up to docs root, then the asset.
    src = "../../" + asset_rel
    alt = (page.meta or {}).get("title") or slug.replace("-", " ").title()
    # PC/NPC images are portraits (floated beside the Overview); locations are banners.
    classes = ".wiki-image"
    if category in ("pcs", "npcs"):
        classes += " .wiki-portrait"
    image_md = f"![{alt}]({src}){{ {classes} }}"

    # Insert right after the first H1; otherwise prepend.
    lines = markdown.split("\n")
    for i, line in enumerate(lines):
        if line.startswith("# "):
            lines.insert(i + 1, "\n" + image_md)
            return "\n".join(lines)

    return image_md + "\n\n" + markdown
